File extension fix.
IETF-Hackathon/pqc-certificates pull request #15
Opened 2022-11-14 07:02 UTC by dghgit

This will build the files with the correct extensions, I think the standing naming is correct as well now. I'm still working on a generate script, but thought I'd send this in now as it's taking longer than expected.

2022-11-14 08:22 UTC, baentsch requested changes
Thanks for these file name changes: This is something (oqs-)check files can work with now. I'd personally thus approve the PR -- but the [README calls for .DER files by default and PEMs only optionally](https://github.com/IETF-Hackathon/pqc-certificates#zip-format-r2): It seems there are some tools that cannot handle PEMs well (@ounsworth : Any insight on this?). So, would it be possible to (also) generate DER's? That's the approach taken in [oqs-gen.sh](https://github.com/IETF-Hackathon/pqc-certificates/blob/6a3dae91fa5cd3796a6f1021e431bb5ac97424ba/providers/oqs/gen.sh#L51-L52).

2022-11-14 11:47 UTC, carl-wallace commented
Re: PEM support, my verifier expected DER initially but I changed that to handle DER or PEM. My generator only emits DER still and I've no plans to change that.

2022-11-14 16:21 UTC, dghgit commented
No problem, I've updated the generator to do both and I've added DER versions for all files.

2022-11-15 06:36 UTC, baentsch approved these changes

2022-11-16 07:47 UTC, merged